### ISSUE TITLE
[IMPROVEMENT] - Embed Scanner in HTML Window

### ISSUE THREAD

**Issue by PabloGBarcelo** [AndreiTelteu/phonegap-plugin-barcodescanner2#2]
Hi!,
I was trying this cordova-plugin and work like a charm!

Maybe in the future will be possible to insert in HTML Element to show preview without need to make fullscreen photo?

Thanks for your job!

**Comment by maswerdna** [comment]
@AndreiTelteu can you look into this please? This would help us and other users to overcome the common problem of Cordova that makes the app die when the camera is launched with a new intent.

**Comment by AndreiTelteu** [comment]
Hi @PabloGBarcelo and @maswerdna  !

I don't maintain this project anymore.

Please checkout this other cordova plugin [bitpay/cordova-plugin-qrscanner](https://github.com/bitpay/cordova-plugin-qrscanner), it worked well when i last used it. Except for some old crosswalk bug.

It allows to have your html app overlayed on top of the qr camera.
